spring:
  application:
    name: libra-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
        show-sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true

server:
  port: ${SERVER_PORT:8082}
